### ISSUE TITLE
Create separate Discord channels for multisig alerts

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1387]
Create independent Discord channels for posting and tracking multisig transactions for the different groups involved on each multisig. As more multisigs are added to the organization it will be increasingly important to reduce the clutter and cleanliness of the review channels to aid reviewers.. Perhaps, creating a `Multisig` section with the following channels (multisigs related noted below each one) makes the most sense for the new stage:

MULTISIG
- Association
    - Association multisig
    - Payments 
- Badger Treasury
    - Vault
    - Voter
    - Ops
- Badger Technical 
    - TechOps
    - Dev
- eBTC
    - Ecosystem
    - TechOps
    - Trops

As more protocols are deployed with their own multisigs, new channels can be created under this structure. The Discord notification bot will have to be adjusted accordingly.

**Comment by ICEBADGER** [comment]
This aligns well with what we had already planned. 

The only issue is that we require one additional level. So we may have to do a Category for each of the sections ( Association, Badger Treasury, Badger Technical, eBTC).  We need the multisig to be at the channel level so that each tx can be a thread. 

Would be ideal if you could have a grouping of Categories to lump them all under Multisig. 

Let me take a look and see what could work.

**Comment by sajanrajdev** [comment]
Closing in favor of https://github.com/Badger-Finance/devops/issues/57
