### ISSUE TITLE
fund llamapay with $usdc and correct streams starting too late

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1489]
streams to councillors were [initialised](https://etherscan.io/tx/0xad720cbed30db1b178c88f5929f4385b0e2512c17f1bc50bee76ad3740a57ae6) in block `19035375`. streams can be publically monitored here: https://gnosis-safe.llamapay.io/salaries/Ethereum/0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e

### retroactive coverage

however, that means that payments from block `18908895` (first one of 2024) to `19035375` still have to be covered.

`126_480 blocks * 12 * amountPerSec(192901234567901235) / 1e20 = 2927.777777777777784336`

ergo:
- [ ] `2927777777` $usdc to be transferred to each of the five councillors that are being streamed;
  - `0xc87e98867B392BDBA50FfCfE53014226FE1fAaE7`
  - `0xae3FB0474841D69AAE9446108F41D01f11E8BeF4`
  - `0xd1911EEDf284BCD3559de6A06ef67233023e0dFe`
  - `0x33Dd3EC6CCB2736dc285bde70aADe5C45bFaD588`
  - `0x3f993093c3917Fe7A117f37cFD008775249f59c8`

### yearly funding

to minimise multisig actions, and to guarantee at least a one year runway, the llamapay contract should be funded for a whole year; `5000 * 5 * 12 = 300_000`. 

- [ ] `0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48.approve(0x3E67cc2C7fFf86d9870dB9D02c43e789B52FB296, 300000000000)`
- [ ] `0x3E67cc2C7fFf86d9870dB9D02c43e789B52FB296.deposit(300000000000)`

**Comment by gosuto-inzasheru** [comment]
as discussed previously, this means it might be good to take this extra 300k into account when rebalancing stables for this period (#1471)

**Comment by sajanrajdev** [comment]
One thing to notice is that this amount per second (0.00192901234567901235) leads to $5k every 30 days, not exactly one month (which I guess has to do with the dynamics of LlamaPay). This means that the 300,000 USDC stream will run for 360 days from its initialization (Jan 18th, 2024), ending on January 12th, 2025. I will keep a note of this date so that we can make sure to begin a conversation around a new stream before this date is reached.

This just makes me wonder @gosuto-inzasheru, if we are compensating for the days between Jan 1st and the 18th, why didn't we setup the stream to cover until Dec 31st, 2024 and make it one year even? Not a big deal but we are basically creating a stream for 1year and 12 days, which is less clean, unless I am missing something.

**Comment by gosuto-inzasheru** [comment]
the streams are indefinite; they dont have an end date

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x3fd37a7fac676b4259c2d6bfeda2563e775d727585b4fbe755e75e778a7fecfd
