### ISSUE TITLE
free up assets stuck in ibbtc peak

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#204]
bvecvx here should be moved to vault: https://etherscan.io/token/0xfd05D3C7fe2924020620A8bE4961bBaA747e6305?a=0x41671ba1abcba387b9b2b752c205e22e916be6e3

**Comment by sajanrajdev** [comment]
New logic with sweeping function has been developed and tested.

Deployed at: https://etherscan.io/address/0x56bb91bfbeeb5400db72bce4c15eb0ddfd06002c#code

**Comment by sajanrajdev** [comment]
@jorijnsmit @petrovska-petro @mitche50, FYI:

19 days ago, 25,000 bveCVX tokens were transferred out of the [bveCVX voting multi](https://etherscan.io/address/0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b#tokentxns). Since this operation includes an on-chain balance check for this token, we needed to ensure that it won't fail.

I re-ran the script using the amount submitted to the Safe within this tx, in the balance checker verification, to ensure that this check will still be valid and won't revert. That is:
```
("verifyBalance(address,address,uint256)", ['0xfd05D3C7fe2924020620A8bE4961bBaA747e6305', '0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b', 69884615940476827071326])
```
Hence,
```
    BALANCE_CHECKER.verifyBalance(
        BVECVX.address, 
        BVECVX_VOTING_MULTI,
        69884615940476827071326
    )
```
The script executed successfully.

The peak contains 19,234.9 bveCVX, the safe currently holds 53,940.8 and the balanceChecker expects minimum 69,884.61 so, as long as we don't withdraw any big amount from now and until its execution, it should be good to go.

**Comment by sajanrajdev** [comment]
New Logic: https://etherscan.io/address/0x56bb91bfbeeb5400db72bce4c15eb0ddfd06002c#code
Old Logic: https://etherscan.io/address/0xbd82a0c250608543b8cacfd4f0e4438438698df6#code

Note that this logic also includes changes to the `_btcToSett` function introduced based on audit results: https://github.com/defidollar/ibbtc/pull/18

Diff: https://www.diffchecker.com/YjOl49wd

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0xa8765b1dfd4b7bd0bde6d4d746e220a8da0bdbd4cdc12a6cec29fb7c89a836ae
