### ISSUE TITLE
Bridge BADGER to Arb & deploy vesting wallet for auto

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#328]
- [x] From `treasury_ops_multisig` bridge or send to EOA to handle (prev @mitche50 had handled it)

- [x] Bridge 11141 badger to Arbitrum

- [x] Seed the vesting wallet with the funds. Start: 1648684800 . Ends: 1656547200

**Comment by jorijnsmit** [comment]
i looked but the anyswap bridge nor router supports badger from mainnet to arbitrum. possible options are the arbitrum default bridge or across.

is there a reason we are not using those scripted, but instead go the eoa route..?

**Comment by petrovska-petro** [comment]
> i looked but the anyswap bridge nor router supports badger from mainnet to arbitrum. possible options are the arbitrum default bridge or across.
> 
> is there a reason we are not using those scripted, but instead go the eoa route..?

no special reason, mainly ease probably, but we can test waters with the bridging from mainent to arb using Across

**Comment by mitche50** [comment]
If I remember correctly when we first started bridging there wasn’t even gnosis support on arb. Definitely should go through msig / scripting now that it is possible though.

**Comment by jorijnsmit** [comment]
working on code that can bridge $badger to arbitrum over its native bridge.

**Comment by jorijnsmit** [comment]
> JasonWan — Yesterday at 6:01 PM
Well, if you have to use the contract to bridge your assets, it does have such a way: first directly call https://developer.offchainlabs.com/docs/sol_contract_docs/md_docs/arb-bridge-eth/bridge/inbox#depositethuint256-maxsubmissioncost-→-uint256-external through the contract, then once the funds arrive on l2, it will arrive to an aliased address, then you need to send a l1-to-l2 tx by create a retryable ticket, this tx’s destAddr is what your real address. The reason you can do this is because every time you send a l1-to-l2 tx, your msg.sender on l2 side is the aliased address, so you can still control this address by send a l1-to-l2 tx(by create retryable ticket). Once you finish those steps, you can then see your funds arrive your l2’s address, and you can enjoy your l2 tx by just call to l2 rpc. (edited)

only way possible currently for a contract to use the arb bridge; this only works for eth. across is not really an option, it just reverts to the native bridge when going from l1 to l2 (the pool is used for speeding up l2 to l1 withdrawals).

i suggest we keep doing this through an eoa for the time being.

progress here for later ref: https://github.com/Badger-Finance/badger-multisig/blob/issue/328/scripts/issue/328/bridge_badger.py

**Comment by jorijnsmit** [comment]
added a tx to one of our eoas in #329

**Comment by petrovska-petro** [comment]
new vesting wallet: https://arbiscan.io/address/0xE5B30AA17D2dcC2141076bbeb1A7724Af308C7F4#contracts

**Comment by mitche50** [comment]
https://etherscan.io/tx/0x638ed30daa6ab81b96ed9e8a85cce61c95b2159b423d293560966b09f6e5e013

Deposit to Arbitrum Bridge

**Comment by mitche50** [comment]
https://arbiscan.io/tx/0x42a9eaca91eb78b2ab281526e55322e52fbb778106405aa74384ce6d9b9fba17 test TX
https://arbiscan.io/tx/0x1d12863d0077edcc36ebdb0b516a52efe19b2e0fb26b35ec90034164dd3c3ca8 full deposit
