### ISSUE TITLE
Redirect wd fee from byvWBTC to treasury

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#540]
Still wd fees are coming to dev_msig, [ref-tx](https://etherscan.io/tx/0x499df01f1c0466da10ac0776d612b58d70d7ec4c8cb0fa150bd69d97a795742c)

change with [method](https://etherscan.io/address/0xc0a972a3cf8e52167589694d135abb66409f9b30#code#L1449)

**Comment by jorijnsmit** [comment]
i would suggest to redirect them to treasury ops; this is where all our other fees are currently going.

**Comment by sajanrajdev** [comment]
Performance and management fees have already been redirected by changing the badger treasury address on Yearn's address book to the DAO's treasury: https://github.com/yearn/yearn-exporter/pull/339

As for withdrawal fees, the byvWBTC contract (the wrapper) is hardcoded to send these to the contract's `affiliate` (which is virtually the contract's governance. This address can't be changed to Trops as originally intended since it would also give this multi the governance rights which doesn't agree with our access control policy, see [comments](https://github.com/Badger-Finance/badger-multisig/pull/542#issuecomment-1152454236).

Instead, we need to upgrade the wrapper's logic to add a `badgerTreasury` function (settable by the affiliate) and modify the withdraw function so that it directs withdrawal fees in its direction. This address will be set to Treasury Ops.

The `byvWBTC`'s proxy admin is the devProxyAdmin so Timelock is required: 
![image](https://user-images.githubusercontent.com/25463788/173098778-af3c6214-724d-4086-91cc-40b867a9d07e.png)

Also, the wrapper's development happened on [badger-system](https://github.com/Badger-Finance/badger-system/blob/master/contracts/yearn/SimpleWrapperGatedUpgradeable.sol) and the logic was never extracted so this could be a good opportunity to do so.

@btcookies, this would also be a good opportunity to introduce GAC pausability to this vault.

CC @dapp-whisperer @petrovska-petro

**Comment by btcookies** [comment]
Logic deployed: https://etherscan.io/address/0x021ea7548ee9b40d57f47706a605043b05c6c92c#code

**Comment by btcookies** [comment]
Nonce 1055
Queued Trace

```
Transaction was Mined 
---------------------
Tx Hash: 0xfa074f65721b2e5f421c52f7be94bb211a6e4c90a35c776b7d386b3bb29a9723
From: 0x15b8Fe651C268cfb5b519cC7E98bd45C162313C2
To: 0xB65cef03b9B89f99517643226d76e286ee999e77
Value: 0
Function: Gnosis Safe.execTransaction
Block: 15084073
Gas Used: 61772 / 99312 (62.2%)

Events In This Transaction
--------------------------
├── IGovernanceTimelock (0x21CF9b77F88Adf8F8C98d7E33Fe601DC57bC0893)
│   └── QueueTransaction
│       ├── txHash: 0x568c1d6fe11ab3320edbc13223a5d0e9ac747eb88349024b13a4797b9f8d6c13
│       ├── target: 0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF
│       ├── value: 0
│       ├── signature: upgrade(address,address)
│       ├── data: 0x0000000000000000000000004b92d19c11435614cd49af1b589001b7c08cd4d5000000000000000000000000021ea7548ee9b40d57f47706a605043b05c6c92c
│       └── eta: 1657563111
│   
└── Gnosis Safe (0xB65cef03b9B89f99517643226d76e286ee999e77)
    └── ExecutionSuccess
        ├── txHash: 0x1ef61c9aac0b93772769c751de8b7385558de79eccc96df595d3316509924037
        └── payment: 0
```

**Comment by btcookies** [comment]
Data pr https://github.com/Badger-Finance/badger-multisig/pull/631

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0xbcfcb05ed152797c08096ae0de5db5083202cea90fe7b4d237f1373639dd5c54

**Comment by btcookies** [comment]
1/3 signed, waiting on approvals

**Comment by gosuto-inzasheru** [comment]
this was never successful? https://etherscan.io/tx/0x67d161383e749759764f4e1ba65e8ab025d1512e0ac752b5b88d607da954e723

**Comment by gosuto-inzasheru** [comment]
looks like we waited too long... will have to be requeued.

![Screenshot 2022-08-02 at 12 35 08](https://user-images.githubusercontent.com/2835259/182354776-ba6367b4-51af-4bf3-b36c-570f146b2679.png)

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x1e3b66a05e9348d3db796df7ab47eef11c6988de89d9dea113c35c6ae6bb49fa#eventlog
