### ISSUE TITLE
upgrade ibbtc fee sink so that rewards go to trops instead of dev msig

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#838]
see https://etherscan.io/address/0x3b823864cd0cbad8a1f2b65d4807906775becaa7#readProxyContract

**Comment by petrovska-petro** [comment]
here is the contract which i think could tackle the upgrade: [repo](https://github.com/petrovska-petro/DisperseUpgrade). let me know guys your thoughts cc: @gosuto-inzasheru @jalbrekt85 @sajanrajdev

**Comment by gosuto-inzasheru** [comment]
what is the original repo? would be nice to see a pr, solidity review or at least a diff.

**Comment by gosuto-inzasheru** [comment]
generated a diff here: https://www.diffchecker.com/tcgQTa4C

but really the solidity review needs to take place somewhere else, ideally in the original repo. if not, as a pr in your new repo but where the changes can be reviewed before merging.

**Comment by petrovska-petro** [comment]
> 

i took this repo as the [ref], reason why i did not push a pr against that repo, it's mainly cause showing the repo in an isolated repo i though will be much cleaner and also that repo somehow is deprecated

**Comment by sajanrajdev** [comment]
What happened with this contract is that it was partially developed by us within the badger-system repo but then it was taken, modified and deplyed by DefiDollar: https://etherscan.io/address/0x52212c14e73a9562579e2b7519926c3d76350f7c#code. This is why we don't have a repo with the latest version and I agree on starting it from scratch. 

@petrovska-petro My advice though, would be to instead of using our latest from badger-system, use their logic from Etherscan to ensure an exact match. I can notice right away that a couple of key components are missing in our version: checking that there are fees to collect and the ability to call "disperse" permissionessly (this is by design):
![image](https://user-images.githubusercontent.com/25463788/197785433-241d52c0-e7c1-47c9-a66b-fc1e4ae23e8f.png)

**Comment by gosuto-inzasheru** [comment]
closing as not done, due to ibbtc deprecating and upgrading will require sigs from dfd as well... much easier to just send some ibbtc from dev to trops once or twice a year.
